#!name=Task cookies- select form nzw9314
#!desc=cookies
#!system=ios

[Script]
# > 豆瓣电影日历 (By @zZPiglet)
http-request ^https:\/\/frodo\.douban\.com\/api\/v\d\/calendar\/today script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/MovieCalendar/MovieCalendar.js

# > 滴滴出行 (By @zZPiglet)
http-request ^https:\/\/as\.xiaojukeji\.com\/ep\/as\/toggles\? script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi.js

# > 饿了么   (By @syzzzf)
http-request ^https:\/\/h5\.ele\.me\/restapi\/eus\/v\d\/current_user$ script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemGetCookies.js

# > 哔哩哔哩番剧监控 (By @lowking0415)
http-request ^https?:\/\/app.bilibili.com\/x\/v2\/space\/bangumi script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bilibili/bangumiMonitor.js

# > 微博通知  (By @zZPiglet)
http-request ^https:\/\/m\.weibo\.cn\/feed\/ script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Weibo/Weibo.js


[MITM]
hostname = %APPEND% frodo.douban.com, as.xiaojukeji.com, h5.ele.me, *.bilibili.com, m.weibo.cn