#!name=Select Tasks
#!desc=fork https://github.com/nzw9314/Surge
#!system=ios

# https://github.com/nzw9314/Surge/blob/master/Module/Task_All_in_one.sgmodule

[Script]
# > 百度签到
#先登录,浏览器访问一下: https://tieba.baidu.com 或者 https://tieba.baidu.com/index/
百度签到(网页) = type=cron,cronexp="0 0 8 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/tieba/tieba.js,script-update-interval=0

# > 哔哩哔哩番剧监控 (By @lowking0415)
哔哩哔哩番剧监控 = type=cron,cronexp="0 1 0,1 * * ?",script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bilibili/bangumiMonitor.js,script-update-interval=0
# 打开浏览器访问: https://www.bilibili.com 或 https://live.bilibili.com
哔哩哔哩 = type=cron,cronexp="35 0 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.js,script-update-interval=0
瓜子转硬币 = type=cron,cronexp="40 0 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/bilibili/bilibili.silver2coin.js,script-update-interval=0
# > 哔哩哔哩大会员特权领取
哔哩哔哩大会员特权领取 = type=cron,cronexp="0 1 0 1 * ?",script-path=https://raw.githubusercontent.com/lowking/Scripts/master/bilibili/privilegeReceive.js,script-update-interval=0

# > 机场签到 (by evilbutcher & Neurogram )
# 使用BoxJs配置订阅及密码
机场签到 = type=cron,cronexp="0 10 0 * * *",script-path=https://raw.githubusercontent.com/evilbutcher/Quantumult_X/master/check_in/glados/checkin_env.js,script-update-interval=0

# > 饿了么   (By @syzzzf)
# 打开 APP, 访问下`我的`>`签到领红包`(左上角)
饿了么 = type=cron,cronexp="30 4 0 * * *",script-path=https://raw.githubusercontent.com/songyangzz/QuantumultX/master/elem/elemSign.js,script-update-interval=0
饿了么-打卡领红包= type=cron,cronexp="00 5 0 * * *",script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js,script-update-interval=0

# > 滴滴出行 (By @zZPiglet)
# 进入"滴滴出行"，若弹出"首次写入滴滴出行 Token 成功"
滴滴出行 = type=cron,cronexp="0 6 0 * * *",script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_new.js,script-update-interval=0
滴滴出行2 = type=cron,cronexp="0 59 23 * * *",script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_reward.js,script-update-interval=0

# 10000
10000 = type=cron,cr=nexp "10 0 0 * * *",script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/10000/10000.js,script-update-interval=0